[package]
name = "romodoro"
version = "0.1.0"
authors = ["Sebastian <sebasheston@gmail.com>"]
edition = "2018"
description = "Rust Pomodoro timer with custom sounds"
license = "mit"

[dependencies]
inotify = "0.7.0"
libnotify = "1.0.3"
rodio = "0.10.0"
clap = "2.33"
config = "0.9"
